using System.Windows;
namespace SmartRAM;
public partial class DiskRecoveryWindow:Window{
 CancellationTokenSource? cts;DiskRecoveryAssessment? assessment;
 public DiskRecoveryWindow(){InitializeComponent();DriveBox.ItemsSource=DiskRecoveryEngine.CandidateDrives();if(DriveBox.Items.Count>0)DriveBox.SelectedIndex=0;}
 async void Scan_Click(object s,RoutedEventArgs e){if(DriveBox.SelectedItem is not string drive)return;cts?.Cancel();cts=new();ScanButton.IsEnabled=false;RepairButton.IsEnabled=false;CancelButton.IsEnabled=true;Status.Text="One-click recovery started — source drive will remain unchanged during diagnosis…";Output.Text="";try{assessment=await DiskRecoveryEngine.AnalyzeAsync(drive,cts.Token);Headline.Text=$"{assessment.Drive} · {assessment.Confidence} recovery confidence";Details.Text=$"Filesystem: {assessment.FileSystem}\nLabel: {assessment.VolumeLabel}\nCapacity: {assessment.Capacity/1073741824d:F1} GB\nAccessible: {assessment.Accessible}\nPhysical disk: {assessment.PhysicalDisk}\nHardware status: {assessment.Health}\nBitLocker locked: {assessment.BitLockerLocked}\n\nProblem: {assessment.Problem}\n\nRecommended action: {assessment.Recommendation}";Evidence.Text=assessment.Evidence;if(assessment.CanUseWindowsRepair){Status.Text="Running Windows read-only filesystem scan…";Output.Text=await DiskRecoveryEngine.ScanFileSystemAsync(drive,cts.Token);RepairButton.IsEnabled=true;Status.Text="Diagnosis complete. Safe repair is available under Advanced repair.";}else{Output.Text="RED RAM protected the source drive. Formatting, initialization and blind write-repair are disabled for this state.\n\nThe current engine could not establish enough filesystem evidence for a safe automatic write repair. No changes were made.";Status.Text="Recovery-first protection active — source drive unchanged.";}}catch(OperationCanceledException){Status.Text="Scan cancelled. No disk changes were made.";}catch(Exception ex){Status.Text="Diagnosis stopped safely.";Output.Text=ex.Message;}finally{ScanButton.IsEnabled=true;CancelButton.IsEnabled=false;}}
 void Cancel_Click(object s,RoutedEventArgs e){cts?.Cancel();CancelButton.IsEnabled=false;Status.Text="Stopping scan safely…";}
 void Repair_Click(object s,RoutedEventArgs e){if(assessment is null||!assessment.CanUseWindowsRepair)return;if(MessageBox.Show($"Repair {assessment.Drive} with Windows CHKDSK /f?\n\nThis writes filesystem metadata. Back up important data first.","Confirm filesystem repair",MessageBoxButton.YesNo,MessageBoxImage.Warning)!=MessageBoxResult.Yes)return;try{var r=DiskRecoveryEngine.StartWindowsRepair(assessment.Drive);Status.Text=r.Message;}catch(Exception ex){MessageBox.Show(ex.Message,"Disk Recovery");}}
 protected override void OnClosed(EventArgs e){cts?.Cancel();cts?.Dispose();base.OnClosed(e);}
}