using System.IO;using System.Windows;using Microsoft.Win32;
namespace SmartRAM;
public partial class FileOrganizerWindow:Window{
 CancellationTokenSource? cts;OrganizerPlan? plan;OrganizerRunResult? lastRun;
 public FileOrganizerWindow(){InitializeComponent();lastRun=LoadLastMove();UndoButton.IsEnabled=lastRun is {Moves.Count:>0};if(lastRun is {Moves.Count:>0})StatusText.Text=$"A previous move with {lastRun.Moves.Count:N0} file(s) can still be undone.";}
 string? PickFolder(){var d=new OpenFolderDialog{Multiselect=false};return d.ShowDialog()==true?d.FolderName:null;}
 void ResetTaskPreview(){cts?.Cancel();plan=null;PreviewGrid.ItemsSource=null;Progress.Value=0;RunButton.IsEnabled=false;UndoButton.IsEnabled=lastRun is {Moves.Count:>0};SummaryText.Text="New task ready. Click 1 · Preview to load the files for this task.";StatusText.Text="Previous task cleared from the screen. No files were changed by clearing the view.";}
 void Source_Click(object s,RoutedEventArgs e){var p=PickFolder();if(p!=null){SourceBox.Text=p;ResetTaskPreview();}}
 void Destination_Click(object s,RoutedEventArgs e){var p=PickFolder();if(p!=null){DestinationBox.Text=p;ResetTaskPreview();}}
 OrganizerStructure Structure()=>StructureBox.SelectedIndex switch{1=>OrganizerStructure.YearMonthType,2=>OrganizerStructure.YearMonth,3=>OrganizerStructure.TypeOnly,4=>OrganizerStructure.DeviceYearMonth,_=>OrganizerStructure.TypeYearMonth};
 OrganizerDateSource DateSource()=>DateBox.SelectedIndex switch{1=>OrganizerDateSource.Created,2=>OrganizerDateSource.Modified,_=>OrganizerDateSource.BestAvailable};
 OrganizerAction Action()=>CopyRadio.IsChecked==true?OrganizerAction.Copy:OrganizerAction.Move;
 string HistoryPath(){var d=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"RED RAM","History");Directory.CreateDirectory(d);return Path.Combine(d,"organizer-last-move.txt");}
 void SaveLastMove(OrganizerRunResult run){try{File.WriteAllLines(HistoryPath(),run.Moves.Select(x=>x.From+"\t"+x.To));}catch{}}
 OrganizerRunResult? LoadLastMove(){try{var p=HistoryPath();if(!File.Exists(p))return null;var moves=File.ReadLines(p).Select(x=>x.Split('\t',2)).Where(x=>x.Length==2).Select(x=>(x[0],x[1])).ToList();return moves.Count==0?null:new OrganizerRunResult(moves.Count,0,0,0,moves);}catch{return null;}}
 void ClearLastMove(){try{var p=HistoryPath();if(File.Exists(p))File.Delete(p);}catch{}}
 async void Preview_Click(object s,RoutedEventArgs e){if(!Directory.Exists(SourceBox.Text)){MessageBox.Show("Choose a valid source folder.");return;}if(string.IsNullOrWhiteSpace(DestinationBox.Text)){MessageBox.Show("Choose one master destination folder.");return;}var src=Path.GetFullPath(SourceBox.Text);var dst=Path.GetFullPath(DestinationBox.Text);if(string.Equals(src,dst,StringComparison.OrdinalIgnoreCase)){if(MessageBox.Show("You selected the same folder as source and destination. RED RAM will create organized subfolders inside it. Continue with preview?","Organize in place",MessageBoxButton.YesNo)!=MessageBoxResult.Yes)return;}cts?.Cancel();cts=new();RunButton.IsEnabled=false;StatusText.Text="Building a safe preview — no files are being changed…";try{var prog=new Progress<(int files,string current)>(x=>StatusText.Text=$"Previewing {x.files:N0} files · {x.current}");plan=await FileOrganizer.PreviewAsync(new(src,dst,Action(),DateSource(),Structure(),SubfoldersCheck.IsChecked==true),prog,cts.Token);PreviewGrid.ItemsSource=plan.Items.Select(x=>new Row(x)).ToList();SummaryText.Text=$"{plan.Items.Count:N0} files · {plan.FolderCount:N0} folders will be created · {plan.Conflicts:N0} conflicts · {plan.Bytes/1073741824d:F2} GB";RunButton.IsEnabled=plan.Items.Count>0;StatusText.Text="Preview ready. Review the destination and conflicts before organizing."; }catch(OperationCanceledException){StatusText.Text="Preview stopped safely.";}catch(Exception ex){MessageBox.Show(ex.Message,"File Organizer");}}
 async void Run_Click(object s,RoutedEventArgs e){if(plan is null)return;var action=Action();var conflicts=plan.Conflicts;if(MessageBox.Show($"{action} {plan.Items.Count-conflicts:N0} files into {plan.FolderCount:N0} organized folders?\n\n{conflicts:N0} filename conflicts will be skipped. RED RAM will not overwrite existing files.","Confirm organization",MessageBoxButton.YesNo,MessageBoxImage.Question)!=MessageBoxResult.Yes)return;cts?.Cancel();cts=new();RunButton.IsEnabled=false;try{var prog=new Progress<(int done,int total,string current)>(x=>{Progress.Value=x.total==0?0:x.done*100d/x.total;StatusText.Text=$"{action}: {x.done:N0}/{x.total:N0} · {x.current}";});lastRun=await FileOrganizer.ExecuteAsync(plan,action,prog,cts.Token);Progress.Value=100;StatusText.Text=$"Complete · {lastRun.Completed:N0} files {action.ToString().ToLowerInvariant()}d · {lastRun.Skipped:N0} skipped · {lastRun.Failed:N0} failed";UndoButton.IsEnabled=action==OrganizerAction.Move&&lastRun.Moves.Count>0;if(action==OrganizerAction.Move){if(lastRun.Moves.Count>0)SaveLastMove(lastRun);else{ClearLastMove();UndoButton.IsEnabled=false;}}MessageBox.Show(StatusText.Text,"RED RAM File Organizer");}catch(OperationCanceledException){StatusText.Text="Organization stopped. Files already completed remain safely in their new location."; }finally{RunButton.IsEnabled=true;}}
 async void Undo_Click(object s,RoutedEventArgs e){if(lastRun is null||lastRun.Moves.Count==0)return;if(MessageBox.Show($"Move {lastRun.Moves.Count:N0} files back to their original locations?","Undo last move",MessageBoxButton.YesNo)!=MessageBoxResult.Yes)return;cts?.Cancel();cts=new();var undo=await FileOrganizer.UndoMovesAsync(lastRun.Moves,cts.Token);if(undo.Remaining.Count==0){ClearLastMove();lastRun=null;UndoButton.IsEnabled=false;StatusText.Text=$"Undo complete · {undo.Restored:N0} files restored.";}else{lastRun=new OrganizerRunResult(undo.Remaining.Count,0,0,0,undo.Remaining);SaveLastMove(lastRun);UndoButton.IsEnabled=true;StatusText.Text=$"Undo restored {undo.Restored:N0} files · {undo.Remaining.Count:N0} still need recovery. RED RAM kept their Undo record.";}}
 void Stop_Click(object s,RoutedEventArgs e)=>cts?.Cancel();
 protected override void OnClosed(EventArgs e){cts?.Cancel();cts?.Dispose();base.OnClosed(e);}
 class Row{readonly OrganizerItem x;public Row(OrganizerItem i){x=i;}public string Name=>Path.GetFileName(x.Source);public string Category=>x.Category;public DateTime Date=>x.Date;public string Device=>x.Device;public string Destination=>x.Destination;public string Note=>x.Note;}
}