using System.IO;
using System.Windows.Media.Imaging;
namespace SmartRAM;
public enum OrganizerAction { Move, Copy }
public enum OrganizerDateSource { BestAvailable, Created, Modified }
public enum OrganizerStructure { TypeYearMonth, YearMonthType, YearMonth, TypeOnly, DeviceYearMonth }
public record OrganizerOptions(string Source,string Destination,OrganizerAction Action,OrganizerDateSource DateSource,OrganizerStructure Structure,bool IncludeSubfolders);
public record OrganizerItem(string Source,string Destination,string Category,DateTime Date,string Device,long Bytes,bool Conflict,string Note);
public record OrganizerPlan(List<OrganizerItem> Items,int Skipped,long Bytes){public int Conflicts=>Items.Count(x=>x.Conflict);public int FolderCount=>Items.Select(x=>Path.GetDirectoryName(x.Destination)).Distinct(StringComparer.OrdinalIgnoreCase).Count();}
public record OrganizerRunResult(int Completed,int Skipped,int Failed,long Bytes,List<(string From,string To)> Moves);public record OrganizerUndoResult(int Restored,List<(string From,string To)> Remaining);
public static class FileOrganizer{
 static readonly HashSet<string> images=new(StringComparer.OrdinalIgnoreCase){".jpg",".jpeg",".png",".gif",".webp",".bmp",".heic",".tif",".tiff",".dng",".raw",".cr2",".cr3",".nef",".arw"};
 static readonly HashSet<string> videos=new(StringComparer.OrdinalIgnoreCase){".mp4",".mkv",".avi",".mov",".wmv",".webm",".m4v",".mts",".3gp"};
 static readonly HashSet<string> audio=new(StringComparer.OrdinalIgnoreCase){".mp3",".wav",".flac",".aac",".m4a",".ogg",".wma"};
 static readonly HashSet<string> docs=new(StringComparer.OrdinalIgnoreCase){".pdf",".doc",".docx",".xls",".xlsx",".ppt",".pptx",".txt",".csv",".rtf"};
 static readonly HashSet<string> archives=new(StringComparer.OrdinalIgnoreCase){".zip",".rar",".7z",".tar",".gz",".iso"};
 static string Cat(string p){var e=Path.GetExtension(p);return images.Contains(e)?"Pictures":videos.Contains(e)?"Videos":audio.Contains(e)?"Audio":docs.Contains(e)?"Documents":archives.Contains(e)?"Archives":"Other";}
 static (DateTime? taken,string? camera) MediaMetadata(string path){try{var ext=Path.GetExtension(path);if(!images.Contains(ext))return(null,null);using var fs=File.Open(path,FileMode.Open,FileAccess.Read,FileShare.ReadWrite|FileShare.Delete);var decoder=BitmapDecoder.Create(fs,BitmapCreateOptions.DelayCreation,BitmapCacheOption.None);if(decoder.Frames.Count==0||decoder.Frames[0].Metadata is not BitmapMetadata m)return(null,null);DateTime? taken=null;if(!string.IsNullOrWhiteSpace(m.DateTaken)&&DateTime.TryParse(m.DateTaken,out var dt)&&dt.Year>1980&&dt<=DateTime.Now.AddDays(1))taken=dt;var make=(m.CameraManufacturer??"").Trim();var model=(m.CameraModel??"").Trim();var camera=string.Join(" ",new[]{make,model}.Where(x=>!string.IsNullOrWhiteSpace(x))).Trim();return(taken,string.IsNullOrWhiteSpace(camera)?null:camera);}catch{return(null,null);}}
 static DateTime PickDate(FileInfo f,OrganizerDateSource s,DateTime? mediaDate)=>s switch{OrganizerDateSource.Created=>f.CreationTime,OrganizerDateSource.Modified=>f.LastWriteTime,_=>mediaDate??(f.LastWriteTime.Year>1980&&f.LastWriteTime<=DateTime.Now.AddDays(1)?f.LastWriteTime:f.CreationTime)};
 static bool Under(string path,string root){var p=Path.GetFullPath(path).TrimEnd(Path.DirectorySeparatorChar)+Path.DirectorySeparatorChar;var r=Path.GetFullPath(root).TrimEnd(Path.DirectorySeparatorChar)+Path.DirectorySeparatorChar;return p.StartsWith(r,StringComparison.OrdinalIgnoreCase);}
 static IEnumerable<string> EnumerateSafe(string root,bool recursive,CancellationToken ct){var pending=new Stack<string>();pending.Push(root);while(pending.Count>0){ct.ThrowIfCancellationRequested();var dir=pending.Pop();IEnumerable<string> fs=Array.Empty<string>(),ds=Array.Empty<string>();try{fs=Directory.EnumerateFiles(dir);}catch{}foreach(var f in fs){ct.ThrowIfCancellationRequested();yield return f;}if(!recursive)continue;try{ds=Directory.EnumerateDirectories(dir);}catch{}foreach(var d in ds)try{if(!File.GetAttributes(d).HasFlag(FileAttributes.ReparsePoint))pending.Push(d);}catch{}}}
 static string Device(FileInfo f,string? camera){if(!string.IsNullOrWhiteSpace(camera))return camera;var n=f.Name.ToLowerInvariant();if(n.Contains("whatsapp"))return "WhatsApp";if(n.Contains("screenshot"))return "Screenshots";return "Unknown device";}
 static string Folder(OrganizerItem x,OrganizerStructure s)=>s switch{OrganizerStructure.TypeYearMonth=>Path.Combine(x.Category,x.Date.Year.ToString(),x.Date.ToString("MMMM")),OrganizerStructure.YearMonthType=>Path.Combine(x.Date.Year.ToString(),x.Date.ToString("MMMM"),x.Category),OrganizerStructure.YearMonth=>Path.Combine(x.Date.Year.ToString(),x.Date.ToString("MMMM")),OrganizerStructure.TypeOnly=>x.Category,OrganizerStructure.DeviceYearMonth=>Path.Combine(x.Device,x.Date.Year.ToString(),x.Date.ToString("MMMM")),_=>x.Category};
 public static Task<OrganizerPlan> PreviewAsync(OrganizerOptions o,IProgress<(int files,string current)>? progress,CancellationToken ct)=>Task.Run(()=>{var list=new List<OrganizerItem>();int skipped=0;long bytes=0;var source=Path.GetFullPath(o.Source);var destination=Path.GetFullPath(o.Destination);bool destinationInsideSource=!source.Equals(destination,StringComparison.OrdinalIgnoreCase)&&Under(destination,source);int n=0;foreach(var p in EnumerateSafe(source,o.IncludeSubfolders,ct)){ct.ThrowIfCancellationRequested();try{if(destinationInsideSource&&Under(p,destination))continue;var f=new FileInfo(p);var meta=MediaMetadata(p);var d=PickDate(f,o.DateSource,meta.taken);var device=Device(f,meta.camera);var temp=new OrganizerItem(p,"",Cat(p),d,device,f.Length,false,"");var dir=Path.Combine(o.Destination,Folder(temp,o.Structure));var dest=Path.Combine(dir,f.Name);bool samePath=Path.GetFullPath(p).Equals(Path.GetFullPath(dest),StringComparison.OrdinalIgnoreCase);bool conflict=!samePath&&(File.Exists(dest)||list.Any(x=>x.Destination.Equals(dest,StringComparison.OrdinalIgnoreCase)));list.Add(temp with{Destination=dest,Conflict=conflict,Note=samePath?"Already in the correct folder — no change needed":conflict?"Name already exists — will be skipped":temp.Device=="Unknown device"?"No reliable camera/device metadata; grouped as Unknown device":meta.taken.HasValue?"Using photo Date Taken metadata":""});bytes+=f.Length;if(++n%100==0)progress?.Report((n,p));}catch{skipped++;}}return new OrganizerPlan(list,skipped,bytes);},ct);
 public static Task<OrganizerRunResult> ExecuteAsync(OrganizerPlan plan,OrganizerAction action,IProgress<(int done,int total,string current)>? progress,CancellationToken ct)=>Task.Run(()=>{int ok=0,skip=0,fail=0;long bytes=0;var moves=new List<(string,string)>();int done=0;var required=plan.Items.Where(x=>!x.Conflict&&!Path.GetFullPath(x.Source).Equals(Path.GetFullPath(x.Destination),StringComparison.OrdinalIgnoreCase)&&(action==OrganizerAction.Copy||!string.Equals(Path.GetPathRoot(Path.GetFullPath(x.Source)),Path.GetPathRoot(Path.GetFullPath(x.Destination)),StringComparison.OrdinalIgnoreCase))).Sum(x=>x.Bytes);var roots=plan.Items.Where(x=>!x.Conflict).Select(x=>Path.GetPathRoot(Path.GetFullPath(x.Destination))).Where(x=>!string.IsNullOrWhiteSpace(x)).Distinct(StringComparer.OrdinalIgnoreCase).ToList();if(roots.Count==1){var drive=new DriveInfo(roots[0]!);if(drive.IsReady&&required>drive.AvailableFreeSpace)throw new IOException($"Destination needs about {required/1073741824d:F1} GB but only {drive.AvailableFreeSpace/1073741824d:F1} GB is free.");}foreach(var x in plan.Items){if(ct.IsCancellationRequested)break;try{if(x.Conflict||!File.Exists(x.Source)||Path.GetFullPath(x.Source).Equals(Path.GetFullPath(x.Destination),StringComparison.OrdinalIgnoreCase)||File.Exists(x.Destination)){skip++;continue;}Directory.CreateDirectory(Path.GetDirectoryName(x.Destination)!);if(action==OrganizerAction.Copy)File.Copy(x.Source,x.Destination,false);else{File.Move(x.Source,x.Destination,false);moves.Add((x.Source,x.Destination));}ok++;bytes+=x.Bytes;}catch{fail++;}finally{progress?.Report((++done,plan.Items.Count,x.Source));}}return new OrganizerRunResult(ok,skip,fail,bytes,moves);},CancellationToken.None);
 public static Task<OrganizerUndoResult> UndoMovesAsync(IEnumerable<(string From,string To)> moves,CancellationToken ct)=>Task.Run(()=>{int restored=0;var remaining=new List<(string,string)>();foreach(var x in moves.Reverse()){if(ct.IsCancellationRequested){remaining.Add(x);continue;}try{if(File.Exists(x.To)&&!File.Exists(x.From)){Directory.CreateDirectory(Path.GetDirectoryName(x.From)!);File.Move(x.To,x.From);restored++;}else if(File.Exists(x.To)||File.Exists(x.From))remaining.Add(x);}catch{remaining.Add(x);}}remaining.Reverse();return new OrganizerUndoResult(restored,remaining);},CancellationToken.None);
}