using System.Diagnostics;
using System.Runtime.InteropServices; using System.Windows; using System.Windows.Media; using System.Windows.Shapes; using System.Windows.Threading;
namespace SmartRAM;
public partial class MainWindow:Window{
 readonly DispatcherTimer timer=new(); readonly List<double> history=new(); readonly List<double> availableHistory=new(); readonly List<double> pagingHistory=new(); PcProfile? profile; BenchResult? bench; PerformanceMonitorService? perf; SmartRamSettings settings=SettingsStore.Load(); bool initializing=true; readonly BaselineSession baseline=new(); readonly MeasurementSession impact=new(); bool measuringAfter; int processRefresh;
 public MainWindow(){InitializeComponent();var totalMb=GetTotalPhysicalMb();bool lowMemory=totalMb<=4096;timer.Interval=TimeSpan.FromSeconds(totalMb<=2048?5:lowMemory?2:1);try{if(totalMb>1536)perf=new PerformanceMonitorService();}catch{} timer.Tick+=(_,_)=>Refresh();timer.Start();StartupCheck.IsChecked=settings.StartWithWindows;UpdateSmartRamControls();initializing=false;Refresh();Loaded+=async(_,_)=>await AnalyzeAsync(false);}
 void UpdateSmartRamControls(){StartSmartRamButton.IsEnabled=!settings.Enabled;StopSmartRamButton.IsEnabled=settings.Enabled;StartSmartRamButton.Content=settings.Enabled?"✓  RED RAM Active":"▶  Start RED RAM";ActiveStatusText.Text=settings.Enabled?"RED RAM is ACTIVE — live monitoring and memory intelligence are running.":"RED RAM is PAUSED — Windows remains in control.";ActiveStatusText.Foreground=settings.Enabled?Brushes.Honeydew:Brushes.LightGray;ActiveDot.Text=settings.Enabled?"●":"○";ActiveDot.Foreground=settings.Enabled?Brushes.MediumSpringGreen:Brushes.Gray;}
 void StartSmartRam_Click(object s,RoutedEventArgs e){if(settings.Enabled)return;settings=settings with{Enabled=true};SettingsStore.Save(settings);UpdateSmartRamControls();StatusText.Text="RED RAM ACTIVE — monitoring and intelligence enabled.";Refresh();}
 void StopSmartRam_Click(object s,RoutedEventArgs e){if(!settings.Enabled)return;settings=settings with{Enabled=false};SettingsStore.Save(settings);UpdateSmartRamControls();StatusText.Text="RED RAM STOPPED — RED RAM monitoring is paused; Windows remains in control.";}
 void Startup_Changed(object s,RoutedEventArgs e){if(initializing)return;bool on=StartupCheck.IsChecked==true;try{SettingsStore.SetStartup(on);settings=settings with{StartWithWindows=on};SettingsStore.Save(settings);StatusText.Text=on?"RED RAM will start with Windows.":"Windows startup disabled.";}catch(Exception ex){MessageBox.Show(ex.Message,"RED RAM");}}
 async void Update_Click(object s,RoutedEventArgs e){UpdateButton.IsEnabled=false;var old=UpdateButton.Content;UpdateButton.Content="Checking…";try{var result=await UpdateService.CheckAsync();StatusText.Text=result.Message;if(result.UpdateAvailable&&result.ReleaseUrl is not null){if(MessageBox.Show(result.Message+"\n\nOpen the official RED RAM release page to install the update?","RED RAM Update",MessageBoxButton.YesNo,MessageBoxImage.Information)==MessageBoxResult.Yes)UpdateService.OpenRelease(result.ReleaseUrl);}else MessageBox.Show(result.Message,"RED RAM Update");}catch(OperationCanceledException){StatusText.Text="Update check cancelled.";}finally{UpdateButton.Content=old;UpdateButton.IsEnabled=true;}}
 void Dashboard_Click(object s,RoutedEventArgs e){StatusText.Text="Dashboard — live memory, pressure, paging, recommendations and PC health are shown here.";}
 void OptimizeNav_Click(object s,RoutedEventArgs e){var detail=profile is null?"Run Analyze PC first so RED RAM can inspect your hardware and current Windows memory configuration.":RecommendationEngine.Build(profile,bench).Detail;MessageBox.Show("SMART OPTIMIZATION\n\n"+detail+"\n\nRED RAM only applies a virtual-memory change after analysis, a storage benchmark, your confirmation and administrator permission. Existing settings are backed up for Restore.","RED RAM · Optimize");}
 async void AnalysisNav_Click(object s,RoutedEventArgs e){await AnalyzeAsync(false);if(profile is not null)MessageBox.Show(ProfileText.Text+"\n\nRECOMMENDATION\n"+RecommendationTitle.Text+"\n"+RecommendationText.Text,"RED RAM · PC Analysis");}
 void ProcessesNav_Click(object s,RoutedEventArgs e){var p=MemoryIntelligenceEngine.TopProcesses();MessageBox.Show("TOP MEMORY USERS\n\n"+p+"\n\nThese are currently using the most memory. High usage does not automatically mean a process is unsafe or should be closed.","RED RAM · Processes");}
 void SettingsNav_Click(object s,RoutedEventArgs e){MessageBox.Show($"SMART RAM SETTINGS\n\nMonitoring: {(settings.Enabled?"Enabled":"Paused")}\nStart with Windows: {(settings.StartWithWindows?"On":"Off")}\n\nUse the controls on the dashboard to change these settings. Windows advanced memory settings can also be opened from the bottom of the dashboard.","RED RAM · Settings");}
 void Organizer_Click(object s,RoutedEventArgs e){var w=new FileOrganizerWindow();w.Show();w.Activate();}
 void Storage_Click(object s,RoutedEventArgs e){var w=new StorageWindow();w.Show();w.Activate();}
 void Recovery_Click(object s,RoutedEventArgs e){var w=new DiskRecoveryWindow{Owner=this};w.Show();w.Activate();}
 void MemorySettings_Click(object s,RoutedEventArgs e){try{Process.Start(new ProcessStartInfo("SystemPropertiesPerformance.exe"){UseShellExecute=true});}catch(Exception ex){MessageBox.Show(ex.Message,"RED RAM");}}
 void Refresh(){var m=new MEMORYSTATUSEX{dwLength=(uint)Marshal.SizeOf<MEMORYSTATUSEX>()};if(!GlobalMemoryStatusEx(ref m))return;double total=m.ullTotalPhys/1073741824d,used=total-m.ullAvailPhys/1073741824d;RamText.Text=$"{total:F1} GB";UsedText.Text=$"{used:F1} GB";PressureText.Text=$"{m.dwMemoryLoad}%";VirtualText.Text=$"{total:F1} GB RAM · {m.ullTotalPageFile/1073741824d:F1} GB commit limit";history.Add(m.dwMemoryLoad);availableHistory.Add(m.ullAvailPhys/1048576d);int historyLimit=GetTotalPhysicalMb()<=2048?60:GetTotalPhysicalMb()<=4096?150:300;if(history.Count>historyLimit){history.RemoveAt(0);availableHistory.RemoveAt(0);}Draw();if(!settings.Enabled){StatusText.Text="RED RAM PAUSED — Windows remains in control.";DiagnosticsText.Text="Live diagnostics paused. Start RED RAM to resume sampling.";IntelligenceText.Text="Memory intelligence paused — no new RED RAM assessment is being generated.";ProcessesText.Text="Process monitoring paused.";ChartStats.Text=$"Physical RAM {total:F1} GB  •  Used {used:F1} GB  •  Pressure {m.dwMemoryLoad}%";PagingStats.Text="Paging sampling paused.";return;} if(perf is not null){try{var s=perf.Sample();pagingHistory.Add(s.PageReadsPerSec+s.PageWritesPerSec);if(pagingHistory.Count>historyLimit)pagingHistory.RemoveAt(0);Draw();DiagnosticsText.Text=$"Commit: {s.CommitPercent:F0}%  •  Available: {s.AvailableMb:F0} MB\nPages/sec: {s.PagesPerSec:F0}  •  Reads/sec: {s.PageReadsPerSec:F0}  •  Writes/sec: {s.PageWritesPerSec:F0}\nDisk latency: {s.DiskLatencyMs:F1} ms  •  CPU: {s.CpuPercent:F0}%"; var a=MemoryIntelligenceEngine.Assess(s,m.dwMemoryLoad); var smart=profile is null?null:MemoryIntelligenceEngine.Recommend(profile,s,m.dwMemoryLoad,bench); IntelligenceText.Text=$"RED RAM Pressure Score: {a.Score}/100 — {a.Level}\nWorkload: {a.Workload}\n{a.Explanation}"+(smart is null?"":$"\nRecommendation: {smart.Action} ({smart.Confidence} confidence)"); ChartStats.Text=$"Used {used:F1} GB  •  Available {m.ullAvailPhys/1073741824d:F1} GB  •  Pressure {m.dwMemoryLoad}%  •  5m min/max {(history.Count>0?history.Min():0):F0}/{(history.Count>0?history.Max():0):F0}%";PagingStats.Text=$"Page reads {s.PageReadsPerSec:F0}/s  •  writes {s.PageWritesPerSec:F0}/s  •  disk {s.DiskLatencyMs:F1} ms";baseline.Add(s,m.dwMemoryLoad); impact.Add(s,m.dwMemoryLoad); if(++processRefresh%(GetTotalPhysicalMb()<=2048?6:5)==0)ProcessesText.Text=MemoryIntelligenceEngine.TopProcesses();}catch{}} StatusText.Text=m.dwMemoryLoad>=85?"High memory pressure detected":"Live monitoring active";}
 async Task AnalyzeAsync(bool runBench){AnalyzeButton.IsEnabled=false;BenchmarkButton.IsEnabled=false;try{StatusText.Text="Detecting hardware and Windows memory configuration…";profile=await Task.Run(SystemProfiler.Scan);if(runBench){StatusText.Text="Benchmarking the pagefile target drive with a temporary 64 MB file…";bench=await StorageBenchmark.RunAsync();}ShowAnalysis();}catch(Exception ex){StatusText.Text="Analysis stopped safely.";MessageBox.Show(ex.Message,"RED RAM analysis");}finally{AnalyzeButton.IsEnabled=true;BenchmarkButton.IsEnabled=true;}}
 void ShowAnalysis(){if(profile is null)return;ProfileText.Text=$"CPU: {profile.Cpu}\nLogical processors: {profile.LogicalCores}\nWindows: {profile.Windows}\nRAM: {profile.RamGb:F1} GB\nSystem storage: {profile.DiskModel}\nType: {profile.DiskKind}\nCapacity/free: {profile.DiskGb:F0} / {profile.FreeGb:F0} GB ({profile.FreePercent:F0}% free)\nPagefile: {profile.PageFile}"+(bench is null?"":$"\nBenchmark: {bench.ReadMbps:F0} MB/s read • {bench.WriteMbps:F0} MB/s write");var r=RecommendationEngine.Build(profile,bench);RecommendationTitle.Text=r.Title;RecommendationText.Text=r.Detail;StatusText.Text=bench is null?"PC analysis complete — run storage benchmark for a stronger recommendation.":"Analysis and storage benchmark complete.";}
 void Draw(){if(Chart.ActualWidth>2&&Chart.ActualHeight>2){Chart.Children.Clear();var p=new Polyline{Stroke=Brushes.DeepSkyBlue,StrokeThickness=2.5};for(int i=0;i<history.Count;i++)p.Points.Add(new Point(i*Math.Max(1,Chart.ActualWidth/299),Chart.ActualHeight-history[i]/100d*Chart.ActualHeight));Chart.Children.Add(p);}if(PagingChart.ActualWidth>2&&PagingChart.ActualHeight>2&&pagingHistory.Count>0){PagingChart.Children.Clear();var max=Math.Max(10,pagingHistory.Max());var p2=new Polyline{Stroke=Brushes.MediumSpringGreen,StrokeThickness=2.5};for(int i=0;i<pagingHistory.Count;i++)p2.Points.Add(new Point(i*Math.Max(1,PagingChart.ActualWidth/299),PagingChart.ActualHeight-pagingHistory[i]/max*PagingChart.ActualHeight));PagingChart.Children.Add(p2);}}
 void Baseline_Click(object s,RoutedEventArgs e){if(!impact.Running){impact.Start();BaselineButton.Content="Save before";StatusText.Text="Recording BEFORE baseline — use the PC normally.";}else{var m=impact.Stop();BaselineButton.Content="Start baseline";if(m is null){MessageBox.Show("Record for at least 5 seconds.");return;}ImpactStore.SaveBefore(m);StatusText.Text="Before baseline saved. It will remain available after restart.";MessageBox.Show($"Saved {m.Samples} samples. Peak RAM {m.PeakPhysicalLoad:F0}%, average commit {m.AverageCommit:F0}%, latency {m.AverageDiskLatency:F1} ms.","RED RAM before baseline");}}
 void After_Click(object s,RoutedEventArgs e){if(!impact.Running){measuringAfter=true;impact.Start();AfterButton.Content="Compare now";StatusText.Text="Recording AFTER measurement — repeat the same workload.";}else if(measuringAfter){var a=impact.Stop();measuringAfter=false;AfterButton.Content="Measure after";var b=ImpactStore.LoadBefore();if(a is null||b is null){MessageBox.Show("A saved before baseline and at least 5 after samples are required.");return;}var d=ImpactStore.Compare(b,a);MessageBox.Show($"{d.Verdict}\nAvailable RAM change: {d.AvailableMbGain:+0;-0;0} MB\nPhysical RAM load change: {d.PhysicalLoadChange:+0.0;-0.0;0}%\nCommit change: {d.CommitChange:+0.0;-0.0;0}%\nDisk latency change: {d.LatencyChange:+0.0;-0.0;0} ms\nPage reads change: {d.PageReadsChange:+0.0;-0.0;0}/s\n\nNegative values mean less pressure/activity. Compare equivalent workloads.","RED RAM impact");StatusText.Text=d.Verdict;}}
 async void Apply_Click(object s,RoutedEventArgs e){if(profile is null){await AnalyzeAsync(true);return;}if(bench is null){MessageBox.Show("Run the storage benchmark first so RED RAM can make a safer recommendation.","RED RAM");return;}var r=RecommendationEngine.Build(profile,bench);if(r.SuggestedGb<=0){MessageBox.Show("RED RAM is working and monitoring your PC. No virtual-memory change is being applied right now.\n\n"+r.Detail+"\n\nThis only affects the optional virtual-memory optimization; RED RAM monitoring remains active.","RED RAM is active");return;}if(!VirtualMemoryManager.IsAdministrator()){if(MessageBox.Show("RED RAM needs administrator permission to change Windows virtual memory. Current settings will be backed up first. Continue?","Administrator permission",MessageBoxButton.YesNo)==MessageBoxResult.Yes)VirtualMemoryManager.RelaunchAsAdmin();return;}var pageRoot=VirtualMemoryManager.PreferredPagefileRoot();if(MessageBox.Show($"RED RAM recommends a {r.SuggestedGb:F0} GB pagefile on {pageRoot} Existing settings will be backed up. A Windows restart is normally required. Apply?","Apply virtual memory",MessageBoxButton.YesNo)!=MessageBoxResult.Yes)return;try{VirtualMemoryManager.Apply(r.SuggestedGb);StatusText.Text="Virtual-memory configuration saved — restart Windows to activate it.";MessageBox.Show("Applied safely. Restart Windows when convenient. RED RAM saved the previous configuration for Restore.","RED RAM");}catch(Exception ex){MessageBox.Show(ex.Message,"RED RAM could not apply the change");}}
 async void Restore_Click(object s,RoutedEventArgs e){if(!VirtualMemoryManager.IsAdministrator()){if(MessageBox.Show("Restoring Windows memory settings requires administrator permission. Continue?","Administrator permission",MessageBoxButton.YesNo)==MessageBoxResult.Yes)VirtualMemoryManager.RelaunchAsAdmin();return;}try{VirtualMemoryManager.Restore();StatusText.Text="Previous virtual-memory configuration restored — restart Windows.";MessageBox.Show("Previous RED RAM backup restored. Restart Windows to complete the change.","RED RAM");}catch(Exception ex){MessageBox.Show(ex.Message,"Restore unavailable");}}
 static double GetTotalPhysicalMb(){var m=new MEMORYSTATUSEX{dwLength=(uint)Marshal.SizeOf<MEMORYSTATUSEX>()};return GlobalMemoryStatusEx(ref m)?m.ullTotalPhys/1048576d:8192;}
 void Chart_SizeChanged(object s,SizeChangedEventArgs e)=>Draw(); async void Analyze_Click(object s,RoutedEventArgs e)=>await AnalyzeAsync(false); async void Benchmark_Click(object s,RoutedEventArgs e)=>await AnalyzeAsync(true);
 protected override void OnClosed(EventArgs e){timer.Stop();perf?.Dispose();base.OnClosed(e);}
 [DllImport("kernel32.dll",SetLastError=true)]static extern bool GlobalMemoryStatusEx(ref MEMORYSTATUSEX x);
 [StructLayout(LayoutKind.Sequential)]struct MEMORYSTATUSEX{public uint dwLength,dwMemoryLoad;public ulong ullTotalPhys,ullAvailPhys,ullTotalPageFile,ullAvailPageFile,ullTotalVirtual,ullAvailVirtual,ullAvailExtendedVirtual;}
}