using System.IO;
using Microsoft.Win32;
using System.Diagnostics;
using System.Security.Principal;
using System.Text.RegularExpressions;
namespace SmartRAM;
public record PagefileBackup(bool Automatic,string PagingFiles);
public record PagefileTargetInfo(string Root,double CapacityGb,double FreeGb,double CurrentAllocatedGb,double ReserveGb,int ConfiguredEntries,bool Automatic);
public static class VirtualMemoryManager {
 const string MM=@"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management";
 public static bool IsAdministrator(){using var id=WindowsIdentity.GetCurrent();return new WindowsPrincipal(id).IsInRole(WindowsBuiltInRole.Administrator);}
 public static PagefileBackup Capture(){using var k=Registry.LocalMachine.OpenSubKey(MM);bool auto=true;try{using var q=new System.Management.ManagementObjectSearcher("SELECT AutomaticManagedPagefile FROM Win32_ComputerSystem");foreach(System.Management.ManagementObject x in q.Get())auto=Convert.ToBoolean(x["AutomaticManagedPagefile"]);}catch{}var a=k?.GetValue("PagingFiles") as string[];return new(auto,a is null?"":string.Join("|",a));}
 public static void SaveBackup(PagefileBackup b){var d=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"SmartRAM");Directory.CreateDirectory(d);File.WriteAllLines(Path.Combine(d,"pagefile-backup.txt"),new[]{b.Automatic.ToString(),b.PagingFiles});}
 public static PagefileBackup? LoadBackup(){var p=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"SmartRAM","pagefile-backup.txt");if(!File.Exists(p))return null;var l=File.ReadAllLines(p);return l.Length>=2?new(bool.Parse(l[0]),l[1]):null;}
 static string? EntryPath(string entry){var m=Regex.Match(entry.Trim(),@"^(?<path>.+?)\s+\d+\s+\d+$");return (m.Success?m.Groups["path"].Value:entry.Trim()).Trim('"');}
 static string[] Entries(PagefileBackup b)=>b.PagingFiles.Split('|',StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries);static void RestorePagingFiles(RegistryKey? k,PagefileBackup b){if(k is null)return;var vals=Entries(b);if(vals.Length>0)k.SetValue("PagingFiles",vals,RegistryValueKind.MultiString);else k.DeleteValue("PagingFiles",false);}
 public static string PreferredPagefileRoot(){var b=Capture();foreach(var entry in Entries(b)){var path=EntryPath(entry);if(string.IsNullOrWhiteSpace(path))continue;try{var root=Path.GetPathRoot(path);if(!string.IsNullOrWhiteSpace(root)){var d=new DriveInfo(root);if(d.IsReady&&d.DriveType==DriveType.Fixed)return root;}}catch{}}return Path.GetPathRoot(Environment.SystemDirectory)!;}
 static double AllocatedOnRoot(string root){double gb=0;try{using var q=new System.Management.ManagementObjectSearcher("SELECT Name,AllocatedBaseSize FROM Win32_PageFileUsage");foreach(System.Management.ManagementObject p in q.Get()){var name=$"{p["Name"]}";var r=Path.GetPathRoot(name);if(!string.IsNullOrWhiteSpace(r)&&r.Equals(root,StringComparison.OrdinalIgnoreCase))gb+=Convert.ToDouble(p["AllocatedBaseSize"]??0)/1024d;}}catch{}return gb;}
 public static PagefileTargetInfo TargetInfo(){var b=Capture();var root=PreferredPagefileRoot();var d=new DriveInfo(root);if(!d.IsReady||d.DriveType!=DriveType.Fixed)throw new InvalidOperationException("SmartRAM only uses a ready fixed drive for virtual memory.");double cap=d.TotalSize/1073741824d,free=d.AvailableFreeSpace/1073741824d,current=AllocatedOnRoot(root);double reserve=Math.Max(10,cap*.10);return new(root,cap,free,current,reserve,Entries(b).Length,b.Automatic);}
 public static void Apply(double gb){if(!IsAdministrator())throw new UnauthorizedAccessException("Administrator permission is required.");if(gb<4||gb>64)throw new ArgumentOutOfRangeException(nameof(gb),"SmartRAM safety limits allow 4–64 GB.");var info=TargetInfo();var verify=TargetInfo();if(!string.Equals(info.Root,verify.Root,StringComparison.OrdinalIgnoreCase))throw new InvalidOperationException("The pagefile target changed during validation. Run analysis again before applying.");info=verify;if(info.ConfiguredEntries>1)throw new InvalidOperationException("SmartRAM found multiple configured pagefiles. To avoid replacing an advanced Windows configuration, automatic Apply is blocked. Review Windows virtual-memory settings manually.");double effectiveFree=info.FreeGb+info.CurrentAllocatedGb;if(effectiveFree-gb<info.ReserveGb)throw new InvalidOperationException($"SmartRAM refused the change because it would leave less than {info.ReserveGb:F0} GB free on {info.Root}");var backup=Capture();SaveBackup(backup);SetAutomatic(false);int mb=(int)Math.Round(gb*1024);try{using var k=Registry.LocalMachine.OpenSubKey(MM,true)??throw new InvalidOperationException("Memory Management registry key unavailable.");k.SetValue("PagingFiles",new[]{$"{info.Root}pagefile.sys {mb} {mb}"},RegistryValueKind.MultiString);}catch{try{SetAutomatic(backup.Automatic);using var rk=Registry.LocalMachine.OpenSubKey(MM,true);RestorePagingFiles(rk,backup);}catch{}throw;}}
 public static void Restore(){if(!IsAdministrator())throw new UnauthorizedAccessException("Administrator permission is required.");var b=LoadBackup()??throw new InvalidOperationException("No SmartRAM backup exists.");var current=Capture();try{SetAutomatic(b.Automatic);using var k=Registry.LocalMachine.OpenSubKey(MM,true)??throw new InvalidOperationException("Memory Management registry key unavailable.");RestorePagingFiles(k,b);}catch{try{SetAutomatic(current.Automatic);using var rk=Registry.LocalMachine.OpenSubKey(MM,true);RestorePagingFiles(rk,current);}catch{}throw;}}
 static void SetAutomatic(bool value){using var cs=new System.Management.ManagementClass("Win32_ComputerSystem");foreach(System.Management.ManagementObject o in cs.GetInstances()){o["AutomaticManagedPagefile"]=value;o.Put();break;}}
 public static void RelaunchAsAdmin(){var psi=new ProcessStartInfo(Environment.ProcessPath!){UseShellExecute=true,Verb="runas"};Process.Start(psi);Environment.Exit(0);}
}
